services:
  database:
    image: mysql:latest
    container_name: grades_app_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql


